// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.22

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.28.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.28.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.28.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.28.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.28.0
	github.com/macrimo/opentelemetry-collector-contrib/receiver/dynatracereceiver v0.0.1
	go.opentelemetry.io/collector-contrib/exporter/loggingexporter v0.122.0
	go.opentelemetry.io/collector/otelcol v0.122.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)





replace github.com/macrimo/opentelemetry-collector-contrib/receiver/dynatracereceiver v0.0.1 => C:\Development\Project_SID\OTel-testms\opentelemetry-collector-contrib\receiver\dynatracereceiver

